### PR TITLE
Nest version update, Support for deleting events, Fixing Cypress tests

### LINKED ISSUE #206: nest conversion -- upgrade Nest to address security vulnerability
Our current version of `@nestjs/common` depends on a vulnerable version of `axios`.

#203 updates the web portal and existing API server.

### LINKED ISSUE #214: nest conversion -- Check Cypress tests
Run the Cypress tests against the UI hooked up to the Nest server to make sure the processes it exercises (mainly just the event management cycle) are implemented.

### LINKED ISSUE #215: nest conversion -- delete endpoint for events
Probably goes in `api-server-nest/src/events/events.authenticated.controller.ts`.

### PR DESCRIPTION
**Pull request by MatthewGidcomb**

### CODE REVIEW

File: api-server-nest/src/events/dto/event-id-response.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+export interface EventIdResponse {
+    id: string,
+    status: 'success' | 'failure'
+}
```
Comment (chriswininger) [inline api-server-nest/src/events/dto/event-id-response.ts]: not a big deal, but nice to end file with a new line

File: api-server-nest/src/events/events.authenticated.controller.ts [hunk 2]
```diff
@@ -56,4 +57,14 @@ export default class EventsAuthenticatedController {
         return this.eventsService.update(id, {verified: true})
             .then(response => response.updatedEntities[0]);
     }
+
+    @Delete(':id')
+    @ApiOperation({summary: 'Delete the event'})
+    @ApiImplicitParam({name: 'id', type: String})
+    deleteEvent(@Param() params: FindByIdParams): Promise<EventIdResponse> {
+        const id = params.id;
```
Comment (chriswininger) [inline api-server-nest/src/events/events.authenticated.controller.ts:65]: This needs an auth guard annotation to make it require an auth  token

File: api-server-nest/src/shared-types/db-delete-response.ts [hunk 3]
```diff
@@ -0,0 +1,7 @@
+export default interface DbDeleteResponse {
+    numberOfAffectedEntities: number
+}
+
```
Comment (chriswininger) [inline api-server-nest/src/shared-types/db-delete-response.ts:4]: ^ thx for the typing

File: api-server-nest/src/shared-types/db-delete-response.ts [hunk 4]
```diff
@@ -0,0 +1,7 @@
...
+export function toDbDeleteResponse(response: number): Promise<DbDeleteResponse> {
+    return Promise.resolve({ numberOfAffectedEntities: response })
+}
```
Comment (chriswininger) [inline api-server-nest/src/shared-types/db-delete-response.ts:7]: I was wondering if we need to wrap in the Promise.resolve or if that's implicit when you return in a .then context.

I've been doing this and was thinking we needed to but then I did some tests on our project at work that seemed to indicate it was superfluous.

It could be dependent on webpack config. What have you seen in this regard @Mathew?

File: api-server-nest/src/events/events.authenticated.controller.ts (hunk 2 above)
Comment (chriswininger) [reply api-server-nest/src/events/events.authenticated.controller.ts:65]: never mind I see that's in the .authenticated controller now.

**Review by chriswininger — APPROVED** [review]
looks good, one small comment and a question
